var annotated_dup =
[
    [ "pynn3", null, [
      [ "PyNN3", "classpynn3_1_1PyNN3.html", "classpynn3_1_1PyNN3" ]
    ] ],
    [ "Activation", "classActivation.html", "classActivation" ],
    [ "Adam", "classAdam.html", "classAdam" ],
    [ "Benchmark", "classBenchmark.html", null ],
    [ "BinaryAccuracy", "classBinaryAccuracy.html", "classBinaryAccuracy" ],
    [ "BinaryCrossEntropyLoss", "classBinaryCrossEntropyLoss.html", "classBinaryCrossEntropyLoss" ],
    [ "BinaryPrecision", "classBinaryPrecision.html", "classBinaryPrecision" ],
    [ "BinaryRecall", "classBinaryRecall.html", "classBinaryRecall" ],
    [ "CategoricalCrossEntropyLoss", "classCategoricalCrossEntropyLoss.html", "classCategoricalCrossEntropyLoss" ],
    [ "IOHelper", "classIOHelper.html", null ],
    [ "LayerNormalization", "classLayerNormalization.html", null ],
    [ "LeakyReLU", "classLeakyReLU.html", "classLeakyReLU" ],
    [ "Linear", "classLinear.html", "classLinear" ],
    [ "Loss", "classLoss.html", "classLoss" ],
    [ "MatMul", "classMatMul.html", null ],
    [ "Matrix", "classMatrix.html", "classMatrix" ],
    [ "MeanAbsoluteError", "classMeanAbsoluteError.html", "classMeanAbsoluteError" ],
    [ "MeanSquaredError", "classMeanSquaredError.html", "classMeanSquaredError" ],
    [ "Metrics", "classMetrics.html", "classMetrics" ],
    [ "MSELoss", "classMSELoss.html", "classMSELoss" ],
    [ "MultiClassAccuracy", "classMultiClassAccuracy.html", "classMultiClassAccuracy" ],
    [ "MultiClassPrecision", "classMultiClassPrecision.html", "classMultiClassPrecision" ],
    [ "MultiClassRecall", "classMultiClassRecall.html", "classMultiClassRecall" ],
    [ "NeuralLayer", "classNeuralLayer.html", "classNeuralLayer" ],
    [ "NeuralNets", "classNeuralNets.html", "classNeuralNets" ],
    [ "None", "classNone.html", null ],
    [ "Normalization", "classNormalization.html", null ],
    [ "OneHotEncoder", "classOneHotEncoder.html", "classOneHotEncoder" ],
    [ "Optimizer", "classOptimizer.html", "classOptimizer" ],
    [ "ReLU", "classReLU.html", "classReLU" ],
    [ "SGD", "classSGD.html", "classSGD" ],
    [ "Sigmoid", "classSigmoid.html", "classSigmoid" ],
    [ "Softmax", "classSoftmax.html", "classSoftmax" ],
    [ "Tanh", "classTanh.html", "classTanh" ]
];